name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner 
      - name: Build and analyze Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"josephmoresena_PInvoke.Extensions" /o:"josephmoresena" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.scanAll=false /d:sonar.coverage.exclusions="**Test.cs,**Tests.cs,**test.cs,**tests.cs,**.SourceGenerator/*.cs" /d:sonar.cs.vstest.reportsPaths=TestResults/*.trx /d:sonar.cs.opencover.reportsPaths=TestResults/*/coverage.opencover.xml /d:sonar.cpd.exclusions="**/NativeUtilities/**FixedAction.cs,**/NativeUtilities/**FixedFunc.cs,**/IManagedBinaryBuffer/StaticCompose.cs,**Test/**Tests**/**.cs"
          dotnet restore src 
          dotnet build src --configuration release 
          dotnet test src --verbosity detailed --collect:"XPlat Code Coverage" --results-directory TestResults/  --logger "trx;verbosity=detailed" --no-build --no-restore --configuration release -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover 
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Patch Buffers ILLink.Substitutions
        working-directory: ./src/Intermediate/Rxmxnx.PInvoke.Buffers.Intermediate/ILLink
        run: sed -i -z 's/Rxmxnx.PInvoke.Buffers.Intermediate/Rxmxnx.PInvoke.Extensions/g;' ILLink.Substitutions.xml
      - name: Pack assembly
        working-directory: ./package
        run: dotnet pack -c Release /p:Version=9999.99.99.99-tmp
        
  run-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: linux-x64 tests
      run: |
          dotnet restore src --runtime linux-x64 
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime linux-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime linux-x64
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime linux-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime linux-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime linux-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime linux-x64
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime linux-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime linux-x64
    - name: linux-arm64 tests
      run: |
          dotnet restore src --runtime linux-arm64 
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime linux-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime linux-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime linux-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime linux-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime linux-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime linux-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime linux-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime linux-arm64
    - name: linux-arm32 tests
      run: |
          dotnet restore src --runtime linux-arm 
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime linux-arm
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime linux-arm
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime linux-arm
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime linux-arm
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime linux-arm
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime linux-arm
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime linux-arm
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime linux-arm
          
  run-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NETRxmxnx.PInvoke.Common.Tests
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: osx-x64 tests
      run: |
          dotnet restore src --runtime osx-x64 
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime osx-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime osx-x64
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime osx-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime osx-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime osx-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime osx-x64
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime osx-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime osx-x64
    - name: osx-arm64 tests
      run: |
          dotnet restore src --runtime osx-arm64 
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime osx-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime osx-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime osx-arm64
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime osx-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime osx-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime osx-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime osx-arm64
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime osx-arm64
        
  run-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: win-x64 tests
      run: |
          dotnet restore src --runtime win-x64 
          dotnet build src/Test/Rxmxnx.PInvoke.Common.Tests --configuration release --runtime win-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime win-x64
          dotnet build src/Test/Rxmxnx.PInvoke.CString.Tests --configuration release --runtime win-x64
          dotnet build src/Test/Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime win-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Common.Tests --runtime win-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Buffers.Tests --runtime win-x64
          dotnet test src/Test/Rxmxnx.PInvoke.CString.Tests --runtime win-x64
          dotnet test src/Test/Rxmxnx.PInvoke.Extensions.Tests --runtime win-x64
    - name: win-x86 tests
      run: |
          dotnet restore src --runtime win-x86 
          dotnet build src\Test\Rxmxnx.PInvoke.Common.Tests --configuration release --runtime win-x86
          dotnet build src\Test\Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime win-x86
          dotnet build src\Test\Rxmxnx.PInvoke.CString.Tests --configuration release --runtime win-x86
          dotnet build src\Test\Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime win-x86
          dotnet test src\Test\Rxmxnx.PInvoke.Common.Tests --runtime win-x86
          dotnet test src\Test\Rxmxnx.PInvoke.Buffers.Tests --runtime win-x86
          dotnet test src\Test\Rxmxnx.PInvoke.CString.Tests --runtime win-x86
          dotnet test src\Test\Rxmxnx.PInvoke.Extensions.Tests --runtime win-x86
    - name: win-arm64 tests
      run: |
          dotnet restore src --runtime win-arm64 
          dotnet build src\Test\Rxmxnx.PInvoke.Common.Tests --configuration release --runtime win-arm64
          dotnet build src\Test\Rxmxnx.PInvoke.Buffers.Tests --configuration release --runtime win-arm64
          dotnet build src\Test\Rxmxnx.PInvoke.CString.Tests --configuration release --runtime win-arm64
          dotnet build src\Test\Rxmxnx.PInvoke.Extensions.Tests --configuration release --runtime win-arm64
          dotnet test src\Test\Rxmxnx.PInvoke.Common.Tests --runtime win-arm64
          dotnet test src\Test\Rxmxnx.PInvoke.Buffers.Tests --runtime win-arm64
          dotnet test src\Test\Rxmxnx.PInvoke.CString.Tests --runtime win-arm64
          dotnet test src\Test\Rxmxnx.PInvoke.Extensions.Tests --runtime win-arm64