name: Release to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SNK_BASE64: ${{ secrets.SN_KEY }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Compile intermediate
      working-directory: ./src/Intermediate
      run: |
          dotnet build -c Release ./Rxmxnx.PInvoke.Common.Intermediate 
          dotnet build -c Release ./Rxmxnx.PInvoke.CString.Intermediate 
          dotnet build -c Release ./Rxmxnx.PInvoke.Extensions.Intermediate
    - name: Extract public key
      working-directory: ./package
      run: echo "${SNK_BASE64}" | base64 -d > Rxmxnx.PInvoke.snk
    - name: Create NuGet Package
      working-directory: ./package
      run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/josephmoresena/Rxmxnx.PInvoke.Extensions/releases/tag/${{ github.event.release.tag_name }}"
    - name: Push NuGet Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
